### ISSUE TITLE
Some .cam files cannot be played

### ISSUE THREAD

**Issue by rsribeiro** [tulio150/tibia-ttm#1]
I have 3 .cam files which cannot be played on Tibia Time Machine. When I try opening it I receive a message saying the files are corrupted.

All 3 files can be opened and played normally using BynaCam and their respective clients, so the files are not indeed corrupted.

[videos.zip](https://github.com/tulio150/tibia-ttm/files/7700204/videos.zip)

The file 8.5_warbane down.cam was recorded with TibiaLive 1.2.
The file 8.55_Saindo de Rook.cam was recorded with TibiaCam TV.
I couldn't find out how the third file was recorded.

**Comment by tulio150** [comment]
The videos created with TibiaCam TV had some extra data that TTM could not parse, it was easy to fix by simply ignoring the data.
The one created with TibiaLive (8.5_warbane) simply cannot be decompressed by the LZMA lib, It is going to take me some time to find the solution. Maybe the program used an older version of the library that compresses different or uses some alternate flags. Can you confirm what version of BynaCam you use to play it, or provide me the app?

**Comment by tulio150** [comment]
Got it, this file had an early EOF on the LZMA data, maybe TibiaLive used a custom implementation of the protocol. The fix is already in the sources and will be included in 6.3

**Comment by rsribeiro** [comment]
Thanks for the speed. I was going to post the bynacam versions when you responded

**Comment by tulio150** [comment]
It's released and ready for using
